name: Daily task

on:
  push:
    branches:
      - master2

jobs:
  pr-title-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_DELETE_TAGS: true